### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by dataubc** [Mahyar-Fazelzadeh/Tetuan_City_power_consumption_analysis#1]
Outstanding work Mahayr, this was one of the most challenging projects for this bootcamp, yet you were able to not only meet all the requirements, but you went above and beyond to accomplish a full fledge project. Congrats.

**Project Structure** 
- It is great that you split the project into few notebooks instead of one giant notebook
- It would be nice to have more comments /summary on the notebooks on the plots that you included essentially this is for the first visualization notebook.

**Data**: 
Time series could be challenging, I like the fact that you did the cross validation correctly, which could be a bit tricky for the time series. When you did `data.info` it would be great if you could discuss that we don't have missing data and how could you tackle the imputation of missing data in time series if they exist. 

**Modeling**
 It is great that you have modes using Arima and RNN. Your comparison and evaluation makes total sense. Good work there.

**Deployment** Good work here as well, but I feel for time series, one would be more interested in a time-widow prediction instead of one point of time prediction. For example, you could ask for how long the user want the forecast to be ad then plot the prediction and download the result as a CSV file.

**Things to do from here**:

If you are interested in digging more about time series, I recommend this [book](https://otexts.com/fpp2/) it is based on R, but you could focus on the theoretical part. For an overview of other package that could be used in time series, check this [article](https://moez-62905.medium.com/top-python-libraries-for-time-series-analysis-in-2022-eebe95913085). Other flavors of NN to try on time series include LSTM and transformers. This is a good introductory into [using transformers for time series](https://towardsdatascience.com/how-to-make-a-pytorch-transformer-for-time-series-forecasting-69e073d4061e)

Finally, it has been a pleasure teaching you these past 3 months, and I wish the best of luck in your next steps.

Mohammed Salama

**Comment by Mahyar-Fazelzadeh** [comment]
Thanks Mohammed for your constructive feedbacks. I will work on your suggestions and will check the other sources you mentioned. 
You know how thankful I am for all of your support and help. Wish you the best.
